# Generated by Django 6.0.4 on 2026-04-29 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_loai', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mã loại')),
                ('ten_loai', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ tên')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('dia_chi', models.TextField(blank=True, null=True, verbose_name='Địa chỉ giao hàng')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dat_hang', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('trang_thai', models.CharField(default='Chờ xử lý', max_length=50)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('nhan_vien_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_hang_tao', to=settings.AUTH_USER_MODEL)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chuc_vu', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_nhap', models.DateTimeField(auto_now_add=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('nguoi_nhap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(max_length=255)),
                ('gia_ban', models.DecimalField(decimal_places=0, max_digits=10)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='san_pham/')),
                ('la_san_pham_moi', models.BooleanField(default=True)),
                ('la_san_pham_noi_bat', models.BooleanField(default=False)),
                ('mo_ta_ngan', models.TextField(blank=True, null=True, verbose_name='Mô tả ngắn')),
                ('uu_dai', models.TextField(blank=True, null=True, verbose_name='Ưu đãi đặc biệt')),
                ('mo_ta_chi_tiet', models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết')),
                ('loai_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loaihang')),
            ],
        ),
        migrations.CreateModel(
            name='NhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_nhap', models.IntegerField()),
                ('ngay_nhap', models.DateTimeField(auto_now_add=True)),
                ('nhan_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.nhanvien')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='KhoHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_ton', models.IntegerField(default=0)),
                ('san_pham', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='HinhAnhSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(upload_to='san_pham_gallery/')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietPhieuNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_nhap', models.IntegerField(default=0)),
                ('phieu_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='api.phieunhap')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_mua', models.IntegerField()),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=10)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.donhang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sanpham')),
            ],
        ),
    ]
