# Generated by Django 6.0.4 on 2026-05-01 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nha_cung_cap', models.CharField(max_length=200, verbose_name='Tên nhà cung cấp')),
                ('so_dien_thoai', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('dia_chi', models.TextField(verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name_plural': 'Nhà Cung Cấp',
            },
        ),
        migrations.AlterModelOptions(
            name='phieunhap',
            options={'verbose_name_plural': 'Phiếu Nhập Kho'},
        ),
        migrations.RemoveField(
            model_name='chitietphieunhap',
            name='so_luong_nhap',
        ),
        migrations.AddField(
            model_name='chitietphieunhap',
            name='gia_nhap',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá nhập'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chitietphieunhap',
            name='so_luong',
            field=models.IntegerField(default=1, verbose_name='Số lượng nhập'),
        ),
        migrations.AddField(
            model_name='phieunhap',
            name='tong_tien',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền nhập'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='ton_kho',
            field=models.IntegerField(default=0, verbose_name='Tồn kho'),
        ),
        migrations.AlterField(
            model_name='chitietphieunhap',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sanpham', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='phieunhap',
            name='ghi_chu',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chú'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phieunhap',
            name='ngay_nhap',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhập'),
        ),
        migrations.AlterField(
            model_name='phieunhap',
            name='nguoi_nhap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người nhập (Admin)'),
        ),
        migrations.AddField(
            model_name='phieunhap',
            name='nha_cung_cap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.nhacungcap', verbose_name='Nhà cung cấp'),
        ),
    ]
