# Generated by Django 6.0.4 on 2026-05-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_nhacungcap_alter_phieunhap_options_and_more'),
    ]

    operations = [
       
    ]
